### ISSUE TITLE
Latest versions of chef do not include activesupport

### ISSUE THREAD

**Issue by joerg** [RiotGamesCookbooks/artifact-cookbook#170]
Is seems that activesupport is somehow needed by nexus_cli but this gem is not included by the latest chef builds by default. I get an error like this

```
    * chef_gem[nexus_cli] action install (up to date)

    ================================================================================
    Error executing action `create` on resource 'artifact_file[rcrs-tools]'
    ================================================================================

    Gem::MissingSpecError
    ---------------------
    Could not find 'activesupport' (>= 3.2.0) among 100 total gem(s)
    Checked in 'GEM_PATH=/root/.gem/ruby/2.1.0:/opt/chef/embedded/lib/ruby/gems/2.1.0', execute `gem env` for more information

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/artifact/libraries/chef_artifact_nexus.rb:10:in `initialize'
    /var/chef/cache/cookbooks/artifact/providers/file.rb:39:in `new'
    /var/chef/cache/cookbooks/artifact/providers/file.rb:39:in `load_current_resource'
```

Chef version is 12.11.18.

**Comment by m2rt** [comment]
Same problem here. Client version 12.12.15
