### ISSUE TITLE
Undefined method 'chef_environment' (looks like from chef_artifact_nexus_configuration library)

### ISSUE THREAD

**Issue by jonathanq** [RiotGamesCookbooks/artifact-cookbook#97]
I just upgraded to 1.10.0, however every time I run chef-client it fails.

```
================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/artifact/resources/deploy.rb
================================================================================


NoMethodError
-------------
undefined method `chef_environment' for nil:NilClass


Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/artifact/libraries/chef_artifact.rb:235:in `encrypted_data_bag_for'
  /var/chef/cache/cookbooks/artifact/libraries/chef_artifact.rb:71:in `data_bag_config_for'
  /var/chef/cache/cookbooks/artifact/libraries/chef_artifact_nexus_configuration.rb:6:in `from_data_bag'
  /var/chef/cache/cookbooks/artifact/resources/deploy.rb:56:in `class_from_file'


Relevant File Content:
----------------------
/var/chef/cache/cookbooks/artifact/libraries/chef_artifact.rb:

228:        # @return [Chef::Mash] the data bag item in Mash form
229:        def encrypted_data_bag_for(node, data_bag)
230:          @encrypted_data_bags = {} unless @encrypted_data_bags
231:
232:          if encrypted_data_bags[data_bag]
233:            return get_from_data_bags_cache(data_bag)
234:          else
235>>           data_bag_item = encrypted_data_bag_item(data_bag, node.chef_environment)
236:            data_bag_item ||= encrypted_data_bag_item(data_bag, WILDCARD_DATABAG_ITEM)
237:            data_bag_item ||= encrypted_data_bag_item(data_bag, "nexus")
238:            data_bag_item ||= {}
239:            @encrypted_data_bags[data_bag] = data_bag_item
240:            return data_bag_item
241:          end
242:        end
243:
244:        # @return [Hash]
```

Looking in the code (https://github.com/RiotGames/artifact-cookbook/blob/master/libraries/chef_artifact_nexus_configuration.rb#L6), nil is being passed in for the node object which then tries to call chef_environment on it.

This might be a different code-path as I am using the S3 deploy method in a Vagrant box (so with an encrypted data_bag, running against chef-server).

If this is just specific to the S3 case, perhaps I should convert the configuration to follow the same model as the new Nexus config?  Going back to a commit before the chef_artifact_nexus_configuration was added fixes it for me.

**Comment by KAllan357** [comment]
This looks like a bug. I think we don't really need to be passing the node object around anymore - likely the methods should be changed to simply pass the environment name.

**Comment by KAllan357** [comment]
@jonathanq Can you give version 1.10.1 a try and let me know if that helps fix your problem?

**Comment by jonathanq** [comment]
Yup - that fixed it, thanks!
